const CardData = [
    {
        id: 1, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/51/card_img/37691/51card.png",
        type: "credit",
        name: "삼성카드 taptap O",
        event: "최대 26.5만원 혜택",
        company: "삼성카드",
        benefit1: "스타벅스",
        benefit2: "대중교통",
        benefit3: "CGV, 롯데시네마",
        benefitcontent1: "50% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "5,000원 할인",
        fee: "국내전용 10,000원 / 해외겸용 10,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드",
        count: "200"
    },
    {
        id: 2, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/13/card_img/28201/13card.png",
        type: "credit",
        name: "신한카드 Mr.Life",
        event: "최대 10만원 캐시백",
        company: "신한카드",
        benefit1: "공과금",
        benefit2: "마트,편의점",
        benefit3: "식음료",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10% 할인",
        fee: "해외겸용 15,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드"
    },
    {
        id: 3, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2669/card_img/32807/2669card.png",
        type: "credit",
        name: "현대카드 M",
        event: "최대 15만원 캐시백",
        company: "현대카드",
        benefit1: "국내외 가맹점",
        benefit2: "온라인 쇼핑몰・일반음식점",
        benefit3: "해외 가맹점",
        benefitcontent1: "1.5% 적립",
        benefitcontent2: "5% 적립",
        benefitcontent3: "5% 적립",
        fee: "국내전용 30,000원 / 해외겸용 30,000원",
        condition: "전월실적 50만원 이상",
        issueType: ""
    },
    {
        id: 4, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2330/card_img/24131/2330card.png",
        type: "credit",
        name: "LOCA 365 카드",
        event: "최대 16만원 캐시백",
        company: "롯데카드",
        benefit1: "아파트관리비, 공과금",
        benefit2: "교통, 통신, 배달앱",
        benefit3: "스트리밍",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "1,500원 할인",
        fee: "국내전용 20,000원 / 해외겸용 20,000원",
        condition: "전월실적 50만원 이상",
        issueType: ""
    },
    {
        id: 5, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/49/card_img/27705/49card.png",
        type: "credit",
        name: "삼성카드 & MILEAGE PLATINUM (스카이패스)",
        event: "",
        company: "삼성카드",
        benefit1: "1,000원당",
        benefit2: "커피/주유",
        benefit3: "인천공항",
        benefitcontent1: "1마일 기본적립",
        benefitcontent2: "2마일 특별적립",
        benefitcontent3: "라운지 무료이용",
        fee: "국내전용 47,000원 / 해외겸용 49,000원",
        condition: "전월실적 없음",
        issueType: ""
    },
    {
        id: 6, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2749/card_img/39221/2749card_4.png",
        type: "debit",
        name: "ONE 체크카드",
        event: "",
        company: "케이뱅크",
        benefit1: "최대",
        benefit2: "자주 쓰는 곳에서",
        benefit3: "3번 결제할 때마다",
        benefitcontent1: "1.2% 캐시백 (3개 중 1개 선택)",
        benefitcontent2: "7% 캐시백 (3개 중 1개 선택)",
        benefitcontent3: "1,000원 캐시백 (3개 중 1개 선택)카드 신청",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: ""
    },
    {
        id: 7, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2422/card_img/27141/2422card.png",
        type: "채크카드",
        name: "노리2 체크카드(KB Pay)",
        event: "최대 4만원 캐시백",
        company: "KB국민카드",
        benefit1: "커피, 모바일, 문화",
        benefit2: "뷰티, 편의점",
        benefit3: "KB Pay",
        benefitcontent1: "10% 할인",
        benefitcontent2: "5% 할인",
        benefitcontent3: "2% 추가 할인",
        fee: "국내전용 없음 / 해외겸용 없음",
        condition: "전월실적 20만원 이상",
        issueType: ""
    },
    {
        id: 8, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/646/card_img/21410/646card.png",
        type: "debit",
        name: "신한카드 Deep Dream 체크(미니언즈)",
        event: "",
        company: "신한카드",
        benefit1: "모두드림",
        benefit2: "더해드림",
        benefit3: "챙겨드림",
        benefitcontent1: "0.2% 적립",
        benefitcontent2: "0.6% 적립",
        benefitcontent3: "1.0% 적립",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: ""
    },
    {
        id: 9, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/286/card_img/20508/286card.png",
        type: "debit",
        name: "카카오페이 신한 체크카드",
        event: "",
        company: "신한카드",
        benefit1: "카카오페이",
        benefit2: "대중교통",
        benefit3: "CGV",
        benefitcontent1: "2% 적립",
        benefitcontent2: "3% 적립",
        benefitcontent3: "최대 3천원 적립",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: ""
    },
    {
        id: 10, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2432/card_img/27295/2432card.png",
        type: "debit",
        name: "네이버페이 머니 하나 체크카드",
        event: "",
        company: "하나카드",
        benefit1: "네이버페이",
        benefit2: "",
        benefit3: "",
        benefitcontent1: "1.2% 포인트 적립",
        benefitcontent2: "",
        benefitcontent3: "",
        fee: "국내전용 없음 / 해외겸용 없음",
        condition: "전월실적 25만원 이상",
        issueType: ""
    },
    {
        id: 11, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/event/301/logo_img/38736/2376card.png",
        type: "credit",
        name: "삼성 iD SIMPLE 카드",
        event: "16만원 캐시백",
        company: "삼성카드",
        benefit1: "국내 외 가맹점",
        benefit2: "온라인쇼핑몰 멤버십",
        benefit3: "영화",
        benefitcontent1: "0.7%·1%할인",
        benefitcontent2: "50%할인",
        benefitcontent3: "3,000원할인",
        fee: "연회비국내전용 7,000원  해외겸용 7,000원",
        condition: "전월실적없음",
        issueType: ""
    },
    {
        id: 12, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2346/card_img/32523/2346card.png",
        type: "credit",
        name: "BC 바로 클리어 플러스",
        event: "최대 15만원 캐시백",
        company: "BC카드",
        benefit1: "점심식사/배달앱",
        benefit2: "온라인쇼핑",
        benefit3: "휴대폰요금/스트리밍",
        benefitcontent1: "7% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10% 할인",
        fee: "국내전용 5,000원 / 해외겸용 5,000원",
        condition: "전월실적 15만원 이상",
        issueType: ""
    },
    {
        id: 13, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/event/222/logo_img/33970/613card.gif",
        type: "credit",
        name: "신한카드 YaY",
        event: "최대 2.6만원 캐시백",
        company: "신한카드",
        benefit1: "배달앱",
        benefit2: "온라인쇼핑",
        benefit3: "홈게임방",
        benefitcontent1: "최대30%적립",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10%적립",
        fee: "국내전용 23,000원  해외겸용 26,000원",
        condition: "전월실적50만원 이상",
        issueType: "VISA"
    },
];

export default CardData;