const CardData = [
    {
        id: 1, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/51/card_img/37691/51card.png",
        type: "credit",
        name: "삼성카드 taptap O",
        event: "최대 26.5만원 혜택",
        company: "삼성카드",
        benefit1: "스타벅스",
        benefit2: "대중교통",
        benefit3: "CGV, 롯데시네마",
        benefitcontent1: "50% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "5,000원 할인",
        fee: "국내전용 10,000원 / 해외겸용 10,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드",
        count: "600",
        release: "2024-01-01"
    },
    {
        id: 2, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/13/card_img/28201/13card.png",
        type: "credit",
        name: "신한카드 Mr.Life",
        event: "최대 10만원 캐시백",
        company: "신한카드",
        benefit1: "공과금",
        benefit2: "마트,편의점",
        benefit3: "식음료",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10% 할인",
        fee: "해외겸용 15,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드",
        count: "668",
        release: "2024-01-01"
    },
    {
        id: 3, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2669/card_img/32807/2669card.png",
        type: "credit",
        name: "현대카드 M",
        event: "최대 15만원 캐시백",
        company: "현대카드",
        benefit1: "국내외 가맹점",
        benefit2: "온라인 쇼핑몰・일반음식점",
        benefit3: "해외 가맹점",
        benefitcontent1: "1.5% 적립",
        benefitcontent2: "5% 적립",
        benefitcontent3: "5% 적립",
        fee: "국내전용 30,000원 / 해외겸용 30,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "420",
        release: "2024-01-01"
    },
    {
        id: 4, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2330/card_img/24131/2330card.png",
        type: "credit",
        name: "LOCA 365 카드",
        event: "최대 16만원 캐시백",
        company: "롯데카드",
        benefit1: "아파트관리비, 공과금",
        benefit2: "교통, 통신, 배달앱",
        benefit3: "스트리밍",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "1,500원 할인",
        fee: "국내전용 20,000원 / 해외겸용 20,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "200",
        release: "2025-01-01"
    },
    {
        id: 5, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/49/card_img/27705/49card.png",
        type: "credit",
        name: "삼성카드 & MILEAGE PLATINUM (스카이패스)",
        event: "",
        company: "삼성카드",
        benefit1: "1,000원당",
        benefit2: "커피/주유",
        benefit3: "인천공항",
        benefitcontent1: "1마일 기본적립",
        benefitcontent2: "2마일 특별적립",
        benefitcontent3: "라운지 무료이용",
        fee: "국내전용 47,000원 / 해외겸용 49,000원",
        condition: "전월실적 없음",
        issueType: "",
        count: "423",
        release: "2025-01-01"
    },
    {
        id: 6, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2749/card_img/39221/2749card_4.png",
        type: "debit",
        name: "ONE 체크카드",
        event: "",
        company: "케이뱅크",
        benefit1: "최대",
        benefit2: "자주 쓰는 곳에서",
        benefit3: "3번 결제할 때마다",
        benefitcontent1: "1.2% 캐시백 (3개 중 1개 선택)",
        benefitcontent2: "7% 캐시백 (3개 중 1개 선택)",
        benefitcontent3: "1,000원 캐시백 (3개 중 1개 선택)카드 신청",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: "",
        count: "9",
        release: "2025-01-01"
    },
    {
        id: 7, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2422/card_img/27141/2422card.png",
        type: "채크카드",
        name: "노리2 체크카드(KB Pay)",
        event: "최대 4만원 캐시백",
        company: "KB국민카드",
        benefit1: "커피, 모바일, 문화",
        benefit2: "뷰티, 편의점",
        benefit3: "KB Pay",
        benefitcontent1: "10% 할인",
        benefitcontent2: "5% 할인",
        benefitcontent3: "2% 추가 할인",
        fee: "국내전용 없음 / 해외겸용 없음",
        condition: "전월실적 20만원 이상",
        issueType: "",
        count: "234",
        release: "2025-01-01"
    },
    {
        id: 8, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/646/card_img/21410/646card.png",
        type: "debit",
        name: "신한카드 Deep Dream 체크(미니언즈)",
        event: "",
        company: "신한카드",
        benefit1: "모두드림",
        benefit2: "더해드림",
        benefit3: "챙겨드림",
        benefitcontent1: "0.2% 적립",
        benefitcontent2: "0.6% 적립",
        benefitcontent3: "1.0% 적립",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: "",
        count: "8",
        release: "2025-01-01"
    },
    {
        id: 9, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/286/card_img/20508/286card.png",
        type: "debit",
        name: "카카오페이 신한 체크카드",
        event: "",
        company: "신한카드",
        benefit1: "카카오페이",
        benefit2: "대중교통",
        benefit3: "CGV",
        benefitcontent1: "2% 적립",
        benefitcontent2: "3% 적립",
        benefitcontent3: "최대 3천원 적립",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: "",
        count: "2",
        release: "2025-01-01"
    },
    {
        id: 10, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2432/card_img/27295/2432card.png",
        type: "debit",
        name: "네이버페이 머니 하나 체크카드",
        event: "",
        company: "하나카드",
        benefit1: "네이버페이",
        benefit2: "",
        benefit3: "",
        benefitcontent1: "1.2% 포인트 적립",
        benefitcontent2: "",
        benefitcontent3: "",
        fee: "국내전용 없음 / 해외겸용 없음",
        condition: "전월실적 25만원 이상",
        issueType: "",
        count: "22",
        release: "2025-01-01"
    },
    {
        id: 11, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2376/card_img/27725/2376card.png",
        type: "credit",
        name: "삼성 iD SIMPLE 카드",
        event: "16만원 캐시백",
        company: "삼성카드",
        benefit1: "국내 외 가맹점",
        benefit2: "온라인쇼핑몰 멤버십",
        benefit3: "영화",
        benefitcontent1: "0.7%·1%할인",
        benefitcontent2: "50%할인",
        benefitcontent3: "3,000원할인",
        fee: "연회비국내전용 7,000원  해외겸용 7,000원",
        condition: "전월실적없음",
        issueType: "",
        count: "1",
        release: "2025-01-02"
    },
    {
        id: 12, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2346/card_img/32523/2346card.png",
        type: "credit",
        name: "BC 바로 클리어 플러스",
        event: "최대 15만원 캐시백",
        company: "BC바로카드",
        benefit1: "점심식사/배달앱",
        benefit2: "온라인쇼핑",
        benefit3: "휴대폰요금/스트리밍",
        benefitcontent1: "7% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10% 할인",
        fee: "국내전용 5,000원 / 해외겸용 5,000원",
        condition: "전월실적 15만원 이상",
        issueType: "",
        count: "12",
        release: "2025-01-02"
    },
    {
        id: 13, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/event/222/logo_img/33970/613card.gif",
        type: "credit",
        name: "신한카드 YaY",
        event: "최대 2.6만원 캐시백",
        company: "신한카드",
        benefit1: "배달앱",
        benefit2: "온라인쇼핑",
        benefit3: "홈게임방",
        benefitcontent1: "최대30%적립",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10%적립",
        fee: "국내전용 23,000원  해외겸용 26,000원",
        condition: "전월실적50만원 이상",
        issueType: "",
        count: "11",
        release: "2024-01-02"
    },
    {
        id: 14, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2759/card_img/37240/2759card.png",
        type: "credit",
        name: "신한카드 처음(ANNIVERSE)",
        event: "최대 16만원 캐시백",
        company: "신한카드",
        benefit1: "음식·생활·패션",
        benefit2: "통신·구독·멤버십",
        benefit3: "소비관리 보너스",
        benefitcontent1: "5% 적립",
        benefitcontent2: "최대 20% 할인",
        benefitcontent3: "매월 최대 1만P",
        fee: "국내전용 15,000원  해외겸용 18,000원",
        condition: "전월실적 30만원 이상",
        issueType: "",
        count: "123",
        release: "2025-01-02"
    },
    {
        id: 15, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2657/card_img/32434/2657card.png",
        type: "credit",
        name: "JADE Classic",
        event: "",
        company: "하나카드",
        benefit1: "바우처 최대",
        benefit2: "전세계 공항라운지",
        benefit3: "국내외 가맹점",
        benefitcontent1: "10만원 제공",
        benefitcontent2: "연 3회 무료 이용",
        benefitcontent3: "1% 하나머니 적립",
        fee: "국내전용 115,000원  해외겸용 120,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "123",
        release: "2025-01-02"
    },
    {
        id: 16, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2692/card_img/33549/2692card.png",
        type: "credit",
        name: "현대카드 Summit",
        event: "20만원 캐시백",
        company: "현대카드",
        benefit1: "국내외 가맹점",
        benefit2: "공항라운지",
        benefit3: "병원・약국",
        benefitcontent1: "1.5% 적립",
        benefitcontent2: "무료 이용",
        benefitcontent3: "5% 적립",
        fee: "국내전용 200,000원  해외겸용 200,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "123",
        release: "2025-01-03"
    },
    {
        id: 17, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2697/card_img/33888/2697card.png",
        type: "credit",
        name: "현대카드 MX Black Edition2",
        event: "20만원 캐시백",
        company: "현대카드",
        benefit1: "국내외 가맹점",
        benefit2: "공항라운지",
        benefit3: "",
        benefitcontent1: "1% 적립",
        benefitcontent2: "무료 이용",
        benefitcontent3: "",
        fee: "국내전용 200,000원  해외겸용 200,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "123",
        release: "2025-01-03"
    },
    {
        id: 18, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2779/card_img/38233/2778card.png",
        type: "credit",
        name: "IBK포인트(신용)",
        event: "최대 2.2만원 캐시백",
        company: "IBK카드",
        benefit1: "국내외 가맹점",
        benefit2: "",
        benefit3: "",
        benefitcontent1: "최대 3.3% 적립",
        benefitcontent2: "",
        benefitcontent3: "",
        fee: "국내전용 21,000원  해외겸용 22,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "123",
        release: "2025-01-03"
    },
    {
        id: 19, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2719/card_img/35783/2719card.jpg",
        type: "credit",
        name: "카드의정석 EVERY DISCOUNT",
        event: "6만원 캐시백 이벤트!",
        company: "우리카드",
        benefit1: "국내외 가맹점",
        benefit2: "국내 온라인 간편결제",
        benefit3: "",
        benefitcontent1: "0.8% 청구할인",
        benefitcontent2: "2% 청구할인",
        benefitcontent3: "",
        fee: "국내전용 12,000원  해외겸용 12,000원",
        condition: "전월실적 없음",
        issueType: "",
        count: "621",
        release: "2025-01-03"
    },
    {
        id: 20, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2663/card_img/32407/2663card.png",
        type: "credit",
        name: "American Express® Gold Card Edition2",
        event: "30만원 상당 혜택",
        company: "현대카드",
        benefit1: "바우처",
        benefit2: "전 세계 공항라운지",
        benefit3: "멤버십리워즈(MR)",
        benefitcontent1: "연간 25만원상당",
        benefitcontent2: "연 10회무료 이용",
        benefitcontent3: "최대 3MR적립",
        fee: "해외겸용 300,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "333",
        release: "2025-01-03"
    },
];

export default CardData;