/**
 * 알고리즘 테스트용 확장된 카드 데이터
 * 실제 운영에서는 데이터베이스/API에서 가져올 메트릭들
 */

// 기존 CardData에 알고리즘 메트릭 추가
const EnhancedCardData = [
    {
        id: 1, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/51/card_img/37691/51card.png",
        type: "credit",
        name: "삼성카드 taptap O",
        event: "최대 26.5만원 혜택",
        company: "삼성카드",
        benefit1: "스타벅스",
        benefit2: "대중교통",
        benefit3: "CGV, 롯데시네마",
        benefitcontent1: "50% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "5,000원 할인",
        fee: "국내전용 10,000원 / 해외겸용 10,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드",
        count: "600",
        release: "2024-01-01",
        // 알고리즘 메트릭
        userRating: 4.5,
        monthlyUsage: 450,
        benefitUsageRate: 0.85,
        clickThroughRate: 0.08,
        conversionRate: 0.035,
        searchVolume: 5400,
        competitorComparison: 0.8,
        stabilityIndex: 0.92,
        userRetentionRate: 0.88,
        volatilityIndex: 0.15,
        consistencyScore: 0.94,
        monthlyStats: [
            { month: 6, users: 480, rating: 4.3 },
            { month: 5, users: 510, rating: 4.4 },
            { month: 4, users: 540, rating: 4.5 },
            { month: 3, users: 570, rating: 4.6 },
            { month: 2, users: 590, rating: 4.5 },
            { month: 1, users: 600, rating: 4.5 }
        ]
    },
    {
        id: 2, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/13/card_img/28201/13card.png",
        type: "credit",
        name: "신한카드 Mr.Life",
        event: "최대 10만원 캐시백",
        company: "신한카드",
        benefit1: "공과금",
        benefit2: "마트,편의점",
        benefit3: "식음료",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "10% 할인",
        fee: "해외겸용 15,000원",
        condition: "전월실적 30만원 이상",
        issueType: "온라인발급 전용 카드",
        count: "668",
        release: "2024-01-01",
        // 알고리즘 메트릭
        userRating: 4.7,
        monthlyUsage: 520,
        benefitUsageRate: 0.90,
        clickThroughRate: 0.09,
        conversionRate: 0.042,
        searchVolume: 6200,
        competitorComparison: 0.85,
        stabilityIndex: 0.95,
        userRetentionRate: 0.91,
        volatilityIndex: 0.12,
        consistencyScore: 0.96,
        monthlyStats: [
            { month: 6, users: 534, rating: 4.5 },
            { month: 5, users: 567, rating: 4.6 },
            { month: 4, users: 601, rating: 4.7 },
            { month: 3, users: 635, rating: 4.8 },
            { month: 2, users: 652, rating: 4.7 },
            { month: 1, users: 668, rating: 4.7 }
        ]
    },
    {
        id: 3, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2669/card_img/32807/2669card.png",
        type: "credit",
        name: "현대카드 M",
        event: "최대 15만원 캐시백",
        company: "현대카드",
        benefit1: "국내외 가맹점",
        benefit2: "온라인 쇼핑몰・일반음식점",
        benefit3: "해외 가맹점",
        benefitcontent1: "1.5% 적립",
        benefitcontent2: "5% 적립",
        benefitcontent3: "5% 적립",
        fee: "국내전용 30,000원 / 해외겸용 30,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "420",
        release: "2024-01-01",
        // 알고리즘 메트릭
        userRating: 4.2,
        monthlyUsage: 380,
        benefitUsageRate: 0.75,
        clickThroughRate: 0.06,
        conversionRate: 0.028,
        searchVolume: 4100,
        competitorComparison: 0.72,
        stabilityIndex: 0.85,
        userRetentionRate: 0.82,
        volatilityIndex: 0.22,
        consistencyScore: 0.88,
        monthlyStats: [
            { month: 6, users: 336, rating: 4.0 },
            { month: 5, users: 357, rating: 4.1 },
            { month: 4, users: 378, rating: 4.2 },
            { month: 3, users: 399, rating: 4.3 },
            { month: 2, users: 410, rating: 4.2 },
            { month: 1, users: 420, rating: 4.2 }
        ]
    },
    {
        id: 4, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2330/card_img/24131/2330card.png",
        type: "credit",
        name: "LOCA 365 카드",
        event: "최대 16만원 캐시백",
        company: "롯데카드",
        benefit1: "아파트관리비, 공과금",
        benefit2: "교통, 통신, 배달앱",
        benefit3: "스트리밍",
        benefitcontent1: "10% 할인",
        benefitcontent2: "10% 할인",
        benefitcontent3: "1,500원 할인",
        fee: "국내전용 20,000원 / 해외겸용 20,000원",
        condition: "전월실적 50만원 이상",
        issueType: "",
        count: "200",
        release: "2025-01-01",
        // 알고리즘 메트릭 (신카드)
        userRating: 4.1,
        monthlyUsage: 85,
        benefitUsageRate: 0.65,
        clickThroughRate: 0.12,
        conversionRate: 0.055,
        searchVolume: 2800,
        competitorComparison: 0.68,
        stabilityIndex: 0.70,
        initialTraction: 0.45,
        growthRate: 0.25,
        marketPenetration: 0.08,
        innovationScore: 0.75,
        competitorAdvantage: 0.72,
        monthlyStats: [
            { month: 3, users: 120, rating: 3.8 },
            { month: 2, users: 160, rating: 4.0 },
            { month: 1, users: 200, rating: 4.1 }
        ]
    },
    {
        id: 5, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/49/card_img/27705/49card.png",
        type: "credit",
        name: "삼성카드 & MILEAGE PLATINUM (스카이패스)",
        event: "",
        company: "삼성카드",
        benefit1: "1,000원당",
        benefit2: "커피/주유",
        benefit3: "인천공항",
        benefitcontent1: "1마일 기본적립",
        benefitcontent2: "2마일 특별적립",
        benefitcontent3: "라운지 무료이용",
        fee: "국내전용 47,000원 / 해외겸용 49,000원",
        condition: "전월실적 없음",
        issueType: "",
        count: "423",
        release: "2025-01-01",
        // 알고리즘 메트릭 (신카드 + 프리미엄)
        userRating: 4.6,
        monthlyUsage: 95,
        benefitUsageRate: 0.88,
        clickThroughRate: 0.10,
        conversionRate: 0.048,
        searchVolume: 3200,
        competitorComparison: 0.85,
        stabilityIndex: 0.75,
        initialTraction: 0.52,
        growthRate: 0.30,
        marketPenetration: 0.12,
        innovationScore: 0.82,
        competitorAdvantage: 0.88,
        monthlyStats: [
            { month: 3, users: 254, rating: 4.4 },
            { month: 2, users: 338, rating: 4.5 },
            { month: 1, users: 423, rating: 4.6 }
        ]
    },
    {
        id: 6, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2749/card_img/39221/2749card_4.png",
        type: "debit",
        name: "ONE 체크카드",
        event: "",
        company: "케이뱅크",
        benefit1: "최대",
        benefit2: "자주 쓰는 곳에서",
        benefit3: "3번 결제할 때마다",
        benefitcontent1: "1.2% 캐시백 (3개 중 1개 선택)",
        benefitcontent2: "7% 캐시백 (3개 중 1개 선택)",
        benefitcontent3: "1,000원 캐시백 (3개 중 1개 선택)카드 신청",
        fee: "해외겸용 없음",
        condition: "전월실적 없음",
        issueType: "",
        count: "9",
        release: "2025-01-01",
        // 알고리즘 메트릭 (신카드 + 낮은 인지도)
        userRating: 4.3,
        monthlyUsage: 12,
        benefitUsageRate: 0.78,
        clickThroughRate: 0.15,
        conversionRate: 0.08,
        searchVolume: 450,
        competitorComparison: 0.65,
        stabilityIndex: 0.60,
        initialTraction: 0.25,
        growthRate: 0.40,
        marketPenetration: 0.02,
        innovationScore: 0.90,
        competitorAdvantage: 0.75,
        monthlyStats: [
            { month: 3, users: 3, rating: 4.0 },
            { month: 2, users: 6, rating: 4.2 },
            { month: 1, users: 9, rating: 4.3 }
        ]
    },
    {
        id: 19, 
        img: "https://d1c5n4ri2guedi.cloudfront.net/card/2719/card_img/35783/2719card.jpg",
        type: "credit",
        name: "카드의정석 EVERY DISCOUNT",
        event: "6만원 캐시백 이벤트!",
        company: "우리카드",
        benefit1: "국내외 가맹점",
        benefit2: "국내 온라인 간편결제",
        benefit3: "",
        benefitcontent1: "0.8% 청구할인",
        benefitcontent2: "2% 청구할인",
        benefitcontent3: "",
        fee: "국내전용 12,000원  해외겸용 12,000원",
        condition: "전월실적 없음",
        issueType: "",
        count: "621",
        release: "2025-01-03",
        // 알고리즘 메트릭 (스테디셀러)
        userRating: 4.4,
        monthlyUsage: 480,
        benefitUsageRate: 0.82,
        clickThroughRate: 0.07,
        conversionRate: 0.038,
        searchVolume: 5100,
        competitorComparison: 0.78,
        stabilityIndex: 0.98,
        userRetentionRate: 0.95,
        volatilityIndex: 0.08,
        consistencyScore: 0.97,
        monthlyStats: [
            { month: 6, users: 615, rating: 4.4 },
            { month: 5, users: 618, rating: 4.4 },
            { month: 4, users: 620, rating: 4.4 },
            { month: 3, users: 619, rating: 4.4 },
            { month: 2, users: 621, rating: 4.4 },
            { month: 1, users: 621, rating: 4.4 }
        ]
    }
];

export default EnhancedCardData;