name: Deploy To EC2

on:
  push:
    branches:
        - main

jobs:
    Deploy:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.ACCESS_TOKEN }} 

            - name: SSH(원격접속)으로 EC2에 접속하기
              uses: appleboy/ssh-action@v1.2.0
              env:
                APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                script_stop: true
                script: |
                    # Git Repository에서 최신 버전 pull
                    cd /home/ec2-user/CardFolio
                    rm -rf src/main/resources/application.properties
                    git pull origin main
                    echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

                    # build gradle
                    ./gradlew clean build

                    # change file name 
                    mv build/libs/*SNAPSHOT.war build/libs/CardFolio.war

                    # WAR 파일을 webapps 디렉토리로 복사
                    mv /home/ec2-user/CardFolio/build/libs/CardFolio.war /home/ec2-user/apache-tomcat-10.1.33/webapps/
                    ls -al /home/ec2-user/apache-tomcat-10.1.33/webapps/

                    # restart tomcat
                    sudo /home/ec2-user/apache-tomcat-10.1.33/bin/shutdown.sh
                    sudo /home/ec2-user/apache-tomcat-10.1.33/bin/startup.sh
                    


